const ActionTypes = {
  RETRIEVE_PLAYERS: 'RETRIEVE_PLAYERS',
  RETRIEVE_PLAYERS_RESPONSE: 'RETRIEVE_PLAYERS_RESPONSE',

  NOTIFY_BUY_IN: 'NOTIFY_BUY_IN',
  NOTIFY_BUY_IN_RESPONSE: 'NOTIFY_BUY_IN_RESPONSE',

  NOTIFY_COUNTER: 'NOTIFY_COUNTER',
  NOTIFY_COUNTER_RESPONSE: 'NOTIFY_COUNTER_RESPONSE',

  PING: 'PING'
};

export default ActionTypes;
