const ActionTypes = {
  RETRIEVE_GAMES: 'RETRIEVE_GAMES',
  RETRIEVE_GAMES_RESPONSE: 'RETRIEVE_GAMES_RESPONSE',
  RETRIEVE_GAME: 'RETRIEVE_GAME',
  RETRIEVE_GAME_RULES_RESPONSE: 'RETRIEVE_GAME_RULES_RESPONSE'
};

export default ActionTypes;
