const ActionTypes = {
  RETRIEVE_GAME_RULES: 'RETRIEVE_GAME_RULES',
  RETRIEVE_GAME_RULES_RESPONSE: 'RETRIEVE_GAME_RULES_RESPONSE',
  RETRIEVE_GAME_RULES_ONE: 'RETRIEVE_GAME_RULES_ONE',
  RETRIEVE_GAME_RULES_ONE_RESPONSE: 'RETRIEVE_GAME_RULES_ONE_RESPONSE'
};

export default ActionTypes;
