const ActionTypes = {
  RETRIEVE_WAGERS: 'RETRIEVE_WAGERS',
  RETRIEVE_WAGERS_RESPONSE: 'RETRIEVE_WAGERS_RESPONSE',
  RETRIEVE_WAGER_RESPONSE: 'RETRIEVE_WAGER_RESPONSE',
  RETRIEVE_ACCOUNTS: 'RETRIEVE_ACCOUNTS',
  RETRIEVE_ACCOUNTS_RESPONSE: 'RETRIEVE_ACCOUNTS_RESPONSE',

  START_WAGER: 'START_WAGER',
  START_WAGER_RESPONSE: 'START_WAGER_RESPONSE',

  COUNTER_WAGER_AND_DEPOSIT: 'COUNTER_WAGER_AND_DEPOSIT',
  COUNTER_WAGER_AND_DEPOSIT_RESPONSE: 'COUNTER_WAGER_AND_DEPOSIT_RESPONSE',

  SET_WAGER_WINNER: 'SET_WAGER_WINNER',
  SET_WAGER_WINNER_RESPONSE: 'SET_WAGER_WINNER_RESPONSE',

  WITHDRAW_WINNINGS: 'WITHDRAW_WINNINGS',
  WITHDRAW_WINNINGS_RESPONSE: 'WITHDRAW_WINNINGS_RESPONSE',

  PING: 'PING'
};

export default ActionTypes;
