const ActionTypes = {
  RETRIEVE_WAGERS: 'RETRIEVE_WAGERS',
  RETRIEVE_WAGERS_RESPONSE: 'RETRIEVE_WAGERS_RESPONSE',
  RETRIEVE_WAGER_RESPONSE: 'RETRIEVE_WAGER_RESPONSE'
};

export default ActionTypes;
