const ActionTypes = {
  RETRIEVE_WAGERS: 'RETRIEVE_WAGERS',
  RETRIEVE_WAGERS_RESPONSE: 'RETRIEVE_WAGERS_RESPONSE',
  RETRIEVE_WAGER_RESPONSE: 'RETRIEVE_WAGER_RESPONSE',
  RETRIEVE_ACCOUNTS: 'RETRIEVE_ACCOUNTS',
  RETRIEVE_ACCOUNTS_RESPONSE: 'RETRIEVE_ACCOUNTS_RESPONSE'
};

export default ActionTypes;
